# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jason\Desktop\Dynamic-Pattern_2_test\SettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(395, 55)
        self.gridLayoutWidget = QtWidgets.QWidget(SettingDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 291, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineedit_position = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_position.setObjectName("lineedit_position")
        self.gridLayout.addWidget(self.lineedit_position, 1, 3, 1, 1)
        self.lineedit_radius = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineedit_radius.setObjectName("lineedit_radius")
        self.gridLayout.addWidget(self.lineedit_radius, 1, 1, 1, 1)
        self.shape_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.shape_label.setObjectName("shape_label")
        self.gridLayout.addWidget(self.shape_label, 0, 0, 1, 1)
        self.color_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.color_label.setObjectName("color_label")
        self.gridLayout.addWidget(self.color_label, 0, 2, 1, 1)
        self.radius_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.radius_label.setObjectName("radius_label")
        self.gridLayout.addWidget(self.radius_label, 0, 1, 1, 1)
        self.comboBox_shape = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_shape.setObjectName("comboBox_shape")
        self.comboBox_shape.addItem("")
        self.comboBox_shape.addItem("")
        self.gridLayout.addWidget(self.comboBox_shape, 1, 0, 1, 1)
        self.position_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.position_label.setMidLineWidth(0)
        self.position_label.setObjectName("position_label")
        self.gridLayout.addWidget(self.position_label, 0, 3, 1, 1)
        self.button_color = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_color.setAutoFillBackground(False)
        self.button_color.setText("")
        self.button_color.setObjectName("button_color")
        self.gridLayout.addWidget(self.button_color, 1, 2, 1, 1)
        self.button_ok = QtWidgets.QPushButton(SettingDialog)
        self.button_ok.setGeometry(QtCore.QRect(310, 10, 75, 23))
        self.button_ok.setObjectName("button_ok")

        self.retranslateUi(SettingDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Dialog"))
        self.shape_label.setText(_translate("SettingDialog", "Shape"))
        self.color_label.setText(_translate("SettingDialog", "Color"))
        self.radius_label.setText(_translate("SettingDialog", "Radius"))
        self.comboBox_shape.setItemText(0, _translate("SettingDialog", "circle"))
        self.comboBox_shape.setItemText(1, _translate("SettingDialog", "square"))
        self.position_label.setText(_translate("SettingDialog", "position"))
        self.button_ok.setText(_translate("SettingDialog", "OK"))
